blank_issues_enabled: false

contact_links:
  - name: GitHub community
    url: https://github.com/afridevelopers/
    about: Contact us via our GitHub community if you found any bug or need any help.
