name: Invite me to the afridevelopers Community

description: I would like to be part of the awesome community

title: "Please invite me to the afridevelopers Community"

labels: [✉️ github-invitation]

body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true

  # - type: input
  #   id: discordname
  #   attributes:
  #     label: Discord Username (if applicable)
  #     placeholder: Insert your Discord username here
  #   validations:
  #     required: false

  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: Where did you meet afridevelopers Community? What do you like about this community? Why do you want to join?
      placeholder: I would like to be part of the awesome community
    validations:
      required: false
