blank_issues_enabled: false

contact_links:
  - name: Linkedin community
    url: https://www.linkedin.com/company/afridevelopers/
    about: Follow us on LinkedIn to stay connected with the community and learn more about AfriDevelopers.
